version: '3.8'
services:
  mongo: 
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: blockchain_auth
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
  blockchain-service: 
    image: blockchain-auth-blockchain-service:latest
    environment:
      PORT: 3022
      MONGO_HOST: mongo
      MONGO_DB_NAME: blockchain_auth
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: 1234
      MONGO_AUTH_SOURCE: admin
      MONGO_DNS_LOOKUP: mongodb
      SEOPOLIA_HTTPS_URL: https://sepolia.infura.io/v3/yourkey
      SEOPOLIA_WSS_URL: wss://sepolia.infura.io/ws/v3/yourkey
    ports:
      - 3022:3022
    volumes:
      - mongodata:/data/db
  identity-service: 
    image: blockchain-auth-identity-service:latest
    environment:
      PORT: 3011
      MONGO_HOST: mongo
      MONGO_DB_NAME: blockchain_auth
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: 1234
      MONGO_AUTH_SOURCE: admin
      MONGO_DNS_LOOKUP: mongodb
      JWT_ACCESS_SECRET: SUPER_SECRET_KEY
      JWT_ACCESS_EXPIRES_IN: 8h
      JWT_REFRESH_SECRET: SUPER_SECRET_KEY_2
      JWT_REFRESH_EXPIRES_IN: 7days
    ports:
      - 3011:3011
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    driver: local