name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Verify lint rules
        run: npm run lint

  test-identity-service:
    needs: lint
    runs-on: ubuntu-latest

    env:
      SEOPOLIA_HTTPS_URL: "seopoloa_https_url"
      SEOPOLIA_WSS_URL: "seopoloa_wss_url"
      JWT_ACCESS_SECRET: "test_secret"
      JWT_ACCESS_EXPIRES_IN: "15m"
      JWT_REFRESH_SECRET: "test_secret2"
      JWT_REFRESH_EXPIRES_IN: "7d"
      MONGO_URI: "mongo_uri"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Run identity service tests
        run:  npm exec nx test identity-service

  test-blockchain-service:
    needs: lint # 
    runs-on: ubuntu-latest

    env:
      SEOPOLIA_HTTPS_URL: "seopoloa_https_url"
      SEOPOLIA_WSS_URL: "seopoloa_wss_url"
      JWT_ACCESS_SECRET: "test_secret"
      JWT_ACCESS_EXPIRES_IN: "15m"
      JWT_REFRESH_SECRET: "test_secret2"
      JWT_REFRESH_EXPIRES_IN: "7d"
      MONGO_URI: "mongo_uri"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Run blockchain service tests
        run:  npm exec nx test blockchain-service
